version: "3.7"

networks:
  private_stack_net:
    driver: bridge

services:
  redis:
    image: redis:5
    networks:
      - private_stack_net
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
  mongo:
    image: mongo:4-xenial
    networks:
      - private_stack_net
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "123456"
    networks:
      - private_stack_net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - private_stack_net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
        reservations:
          cpus: '0.25'
          memory: 512M
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - private_stack_net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
  hfxeventstash:
    image: gamaops/hfxeventstash:stable
    environment:
      LOG_LEVEL: debug
    ports:
      - "42043:42043"
    volumes:
      - ./hfxeventstash-logstash.conf:/usr/src/hfxeventstash/lib/logstash.conf
      - /tmp/protos:/var/lib/hfxeventstash/protos
    networks:
      - private_stack_net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M